README.md, lib/scraped_page_archive.rb, lib/scraped_page_archive/open-uri.rb
Move the monkey patches for `open-uri` into a separate file so that they're disabled by default.
Fixes https://github.com/everypolitician/scraped_page_archive/issues/6
=> Make open-uri hooks optional

lib/scraped_page_archive.rb
This ensures that even if we don't use VCR (if we can't detect the git
repository url, for example) HTTP requests are still allowed to be
performed.
Fixes #11
=> Allow HTTP connections when no VCR cassette in use

lib/scraped_page_archive.rb, test/scraped_page_archive_test.rb, test/test_helper.rb
This changes the behaviour of `git_remote_get_url_origin` to return `nil` if the child process exits with a non-zero status code. I've also added some tests for this method so it doesn't break again in the future.
Fixes #10
=> Dont assume we're operating in a git repo

lib/scraped_page_archive.rb
This is needed because git will refuse to commit if this isn't set.
Fixes #15
=> Set git user.name option after cloning

lib/scraped_page_archive.rb
We don't have access to pry when the scrapers are running on morph, so
it's more useful to just print out any errors so they can be debugged.
=> Don't rescue commit errors with pry

lib/scraped_page_archive.rb, lib/scraped_page_archive/version.rb, test/scraped_page_archive_test.rb
This makes it more intuitive to use it in a script where you change
between reading from an archive and writing to an archive, instead of
modifying the state globally you just modify it for the instance you're
working with.
I've kept the shorthand for `ScrapedPageArchive.record`, so for the
simple case it will continue to function as before.
Part of the groundwork for #21
=> Change ScrapedPageArchive to be a class

lib/scraped_page_archive.rb
This change means that you can force the GitHub url to be a certain
value by setting an environment variable. This wasn't possible
previously as it would automatically use the `git remote` url and then
fallback to the environment variable.
=> Get GitHub url from environment variable first

CHANGELOG.md, README.md, lib/scraped_page_archive/capybara.rb, lib/scraped_page_archive/version.rb
Overload the visit method of capybara to save html and yml files of the
content of visited pages. Should work in poltergiest based scrapers by
requiring `scraped_page_archive/capybara`.
=> add support for capybara poltergeist based scrapers

lib/scraped_page_archive.rb
This adds a `ScrapedPageArchive#open_from_archive` method which acts just like `open-uri` but will return pages from the archive instead of performing an actual http request. If the page doesn't exist in the archive then an error is raised.
In the future we could potentially have an option that will go and perform the live request if it's not in the archive, but for now I think it's better to fail noisily so we can see what conditions we might want to perform a live request under.
Part of #21
=> Add method for getting pages back out of the archive

lib/scraped_page_archive.rb
This change uses the Ruby 2.0.0 interface for adding headers to an
open-uri response, which is to join them together with ', ' so that
they're in string format, rather than as an array.
We need to do it this way because it wasn't until Ruby 2.1 that open-uri
learned how to deal with headers that have multiple values.
=> Fix Ruby 2.0.0 compatibility

lib/scraped_page_archive.rb
This change fixes a bug where we were recording to the wrong directory
and not capturing the results correctly.
We need to configure VCR::Archive before we perform the VCR operations.
This ensures that the archive is saved to the correct directory.
Part of the fix for #30
=> Ensure storage location is set before running VCR

lib/scraped_page_archive/capybara.rb
This fixes the Capybara adapter to reference local variables rather than
trying to call methods on 'page'. Previously we had this functionality
in Capybara::Poltergeist::Driver, which has a 'page' variable, but we
moved it to Capybara::Poltergeist::Browser, and therefore no longer need
to call methods on 'page' as we can call them directly.
Fixes #30
=> Remove references to page in capybara adapter

README.md
People wanting to use `open-uri` were using the `record`
block instead because they stopped reading once they
saw something that looked like what they should do, when
what they needed was much simpler. This commit reorders
the usage examples to (hopefully) avoid that.
Closes #22
=> Update README to reorder usage examples

bin/console
We already had pry in the gemspec, I'd just forgotten to enable it in `bin/console`. This change fixes that.
=> Switch to using pry in bin/console

README.md, lib/scraped_page_archive.rb, lib/scraped_page_archive/git_storage.rb, test/scraped_page_archive_test.rb
This introduces a new `GitStorage` class which is an extraction of the git parts of the `ScrapedPageArchive` class. This should make it easier to test the git parts of this gem in isolation. It also means there is looser coupling between `ScrapedPageArchive` and `git`.
This change was spurred on by https://github.com/everypolitician/scraped_page_archive/pull/40#discussion_r80220902.
=> Extract git operations into a separate storage class

lib/scraped_page_archive.rb
When there is a problem in a morph scraper that is using the archiver, and the problem is either the morph environment variable has the wrong name or the url is wrong, the gem will print an error message that may be considered not very helpful.
This PR takes @davewhiteland 's suggestion in #45 to make it clearer.
Closes #45
=> Improve the error message when the repo url is wrong

lib/scraped_page_archive/git_storage.rb
GitStorage was trying to reference a `ret` variable which doesn't exist,
which meant that when there were no files to commit it would raise an
exception and stop the scraper.
Fixes #48 
I did try adding a regression test for this, but the `GitStorage` class tries to clone a repo before doing any operations on it. Trying to work around that in tests turned out to be a bit of a rabbit hole.
I think this is OK, since the plan is to try and tease bits of this repository out into separate tools which each focus on one job, at which point we can re-think how the git storage tool will work and write some tests for it as appropriate.
=> Remove reference to variable that doesn't exist

CHANGELOG.md, lib/scraped_page_archive/capybara.rb, lib/scraped_page_archive/open-uri.rb
This makes it so we only create one instance of `ScrapedPageArchive::GitStorage` and therefore only have to clone the git repo once, rather than once _per request_.
This should give a fairly significant speed boost to existing scrapers.
Fixes #52
=> Don't re-clone repo on each request

.travis.yml, README.md
This change means that when Travis notices a new tag that points to a commit on the `master` branch it will automatically release that tag to RubyGems as a new version. See the [Travis RubyGems Deployment docs](https://docs.travis-ci.com/user/deployment/rubygems) for more details.
This configuration uses a `$RUBYGEMS_API_KEY` variable, which I've set on Travis from the command line using the following command:
travis env set RUBYGEMS_API_KEY insert_api_key_here
I got the API key from https://rubygems.org/profile/edit, I used an everypolitician specific RubyGems account that I created, the password is on the internal mySociety wiki.
=> Enable RubyGems deployment from Travis CI

README.md
This remove the docs that tell your to use `rake release` to push to RubyGems. These aren't needed now that the releases are done on Travis (#56).
=> Remove old release docs from README

CHANGELOG.md
This changes the release date for `v0.5.0` in `CHANGELOG.md` to today's date, which is when that version ended up getting released.
Related to #55
=> Fix release date for v0.5.0 in CHANGELOG
